<a href="https://www.kaggle.com/code/gauravduttakiit/pss4e7-basic-cleanup?scriptVersionId=188626573" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
train=pd.read_csv('/kaggle/input/playground-series-s4e7/train.csv')
train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   0    Male   21                1         35.0                   0   
1   1    Male   43                1         28.0                   0   
2   2  Female   25                1         14.0                   1   
3   3  Female   35                1          1.0                   0   
4   4  Female   36                1         15.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes         65101.0                 124.0      187   
1   > 2 Years            Yes         58911.0                  26.0      288   
2    < 1 Year             No         38043.0                 152.0      254   
3    1-2 Year            Yes          2630.0                 156.0       76   
4    1-2 Year             No         31951.0                 152.0      294   

   Response  
0         0  
1         1  
2         0  
3         0  
4         0

In [2]:
test=pd.read_csv('/kaggle/input/playground-series-s4e7/test.csv')
test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  11504798  Female   20                1         47.0                   0   
1  11504799    Male   47                1         28.0                   0   
2  11504800    Male   47                1         43.0                   0   
3  11504801  Female   22                1         47.0                   1   
4  11504802    Male   51                1         19.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    < 1 Year             No          2630.0                 160.0      228  
1    1-2 Year            Yes         37483.0                 124.0      123  
2    1-2 Year            Yes          2630.0                  26.0      271  
3    < 1 Year             No         24502.0                 152.0      115  
4    1-2 Year             No         34115.0                 124.0      148

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11504798 entries, 0 to 11504797
Data columns (total 12 columns):
 #   Column                Dtype  
---  ------                -----  
 0   id                    int64  
 1   Gender                object 
 2   Age                   int64  
 3   Driving_License       int64  
 4   Region_Code           float64
 5   Previously_Insured    int64  
 6   Vehicle_Age           object 
 7   Vehicle_Damage        object 
 8   Annual_Premium        float64
 9   Policy_Sales_Channel  float64
 10  Vintage               int64  
 11  Response              int64  
dtypes: float64(3), int64(6), object(3)
memory usage: 1.0+ GB


In [4]:
train.nunique().sort_values(ascending=False)

id                      11504798
Annual_Premium             51728
Vintage                      290
Policy_Sales_Channel         152
Age                           66
Region_Code                   54
Vehicle_Age                    3
Gender                         2
Driving_License                2
Previously_Insured             2
Vehicle_Damage                 2
Response                       2
dtype: int64

In [5]:
train=train.drop(['id'],axis=1)
train.head()

Gender  Age  Driving_License  Region_Code  Previously_Insured Vehicle_Age  \
0    Male   21                1         35.0                   0    1-2 Year   
1    Male   43                1         28.0                   0   > 2 Years   
2  Female   25                1         14.0                   1    < 1 Year   
3  Female   35                1          1.0                   0    1-2 Year   
4  Female   36                1         15.0                   1    1-2 Year   

  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response  
0            Yes         65101.0                 124.0      187         0  
1            Yes         58911.0                  26.0      288         1  
2             No         38043.0                 152.0      254         0  
3            Yes          2630.0                 156.0       76         0  
4             No         31951.0                 152.0      294         0

In [6]:
test=test.drop(['id'],axis=1)
test.head()

Gender  Age  Driving_License  Region_Code  Previously_Insured Vehicle_Age  \
0  Female   20                1         47.0                   0    < 1 Year   
1    Male   47                1         28.0                   0    1-2 Year   
2    Male   47                1         43.0                   0    1-2 Year   
3  Female   22                1         47.0                   1    < 1 Year   
4    Male   51                1         19.0                   0    1-2 Year   

  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0             No          2630.0                 160.0      228  
1            Yes         37483.0                 124.0      123  
2            Yes          2630.0                  26.0      271  
3             No         24502.0                 152.0      115  
4             No         34115.0                 124.0      148

In [7]:
round(train['Response'].value_counts()*100/len(train),2)

Response
0    87.7
1    12.3
Name: count, dtype: float64

In [8]:
train.isnull().sum()

Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [9]:
train['Vehicle_Age'].value_counts()

Vehicle_Age
1-2 Year     5982678
< 1 Year     5044145
> 2 Years     477975
Name: count, dtype: int64

In [10]:
train['Vehicle_Age']=train['Vehicle_Age'].replace({'1-2 Year':1,
                                                   '> 2 Years':2, 
                                                   '< 1 Year':0})
train['Vehicle_Age'].value_counts()

/tmp/ipykernel_18/276297216.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Vehicle_Age']=train['Vehicle_Age'].replace({'1-2 Year':1,


Vehicle_Age
1    5982678
0    5044145
2     477975
Name: count, dtype: int64

In [11]:
test['Vehicle_Age']=test['Vehicle_Age'].replace({'1-2 Year':1,
                                                   '> 2 Years':2, 
                                                   '< 1 Year':0})
test['Vehicle_Age'].value_counts()

/tmp/ipykernel_18/2808027606.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Vehicle_Age']=test['Vehicle_Age'].replace({'1-2 Year':1,


Vehicle_Age
1    3989276
0    3361255
2     319335
Name: count, dtype: int64

In [12]:
train['Gender'].value_counts()

Gender
Male      6228134
Female    5276664
Name: count, dtype: int64

In [13]:
train['Gender']=train['Gender'].replace({'Male':0,
                                         'Female':1})
train['Gender'].value_counts()

/tmp/ipykernel_18/1311896529.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Gender']=train['Gender'].replace({'Male':0,


Gender
0    6228134
1    5276664
Name: count, dtype: int64

In [14]:
test['Gender']=test['Gender'].replace({'Male':0,
                                         'Female':1})
test['Gender'].value_counts()

/tmp/ipykernel_18/3059260769.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Gender']=test['Gender'].replace({'Male':0,


Gender
0    4151402
1    3518464
Name: count, dtype: int64

In [15]:
train['Vehicle_Damage'].value_counts()

Vehicle_Damage
Yes    5783229
No     5721569
Name: count, dtype: int64

In [16]:
train['Vehicle_Damage']=train['Vehicle_Damage'].replace({'Yes':1,
                                                        'No':0})
train['Vehicle_Damage'].value_counts()

/tmp/ipykernel_18/1728548997.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Vehicle_Damage']=train['Vehicle_Damage'].replace({'Yes':1,


Vehicle_Damage
1    5783229
0    5721569
Name: count, dtype: int64

In [17]:
test['Vehicle_Damage']=test['Vehicle_Damage'].replace({'Yes':1,
                                                        'No':0})
test['Vehicle_Damage'].value_counts()

/tmp/ipykernel_18/1147790440.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Vehicle_Damage']=test['Vehicle_Damage'].replace({'Yes':1,


Vehicle_Damage
1    3854463
0    3815403
Name: count, dtype: int64

In [18]:
train.head()

Gender  Age  Driving_License  Region_Code  Previously_Insured  Vehicle_Age  \
0       0   21                1         35.0                   0            1   
1       0   43                1         28.0                   0            2   
2       1   25                1         14.0                   1            0   
3       1   35                1          1.0                   0            1   
4       1   36                1         15.0                   1            1   

   Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response  
0               1         65101.0                 124.0      187         0  
1               1         58911.0                  26.0      288         1  
2               0         38043.0                 152.0      254         0  
3               1          2630.0                 156.0       76         0  
4               0         31951.0                 152.0      294         0

In [19]:
train[['Region_Code','Policy_Sales_Channel']].describe().apply(lambda s: s.apply('{0:.1f}'.format))

Region_Code Policy_Sales_Channel
count  11504798.0           11504798.0
mean         26.4                112.4
std          13.0                 54.0
min           0.0                  1.0
25%          15.0                 29.0
50%          28.0                151.0
75%          35.0                152.0
max          52.0                163.0

In [20]:
test[['Region_Code','Policy_Sales_Channel']].describe().apply(lambda s: s.apply('{0:.1f}'.format))

Region_Code Policy_Sales_Channel
count   7669866.0            7669866.0
mean         26.4                112.4
std          13.0                 54.1
min           0.0                  1.0
25%          15.0                 29.0
50%          28.0                151.0
75%          35.0                152.0
max          52.0                163.0

In [21]:
list(set(train["Region_Code"].unique().tolist())^set(test["Region_Code"].unique().tolist()))

[39.2]

In [22]:
len(sorted(train['Region_Code'].unique().tolist())),len(sorted(test['Region_Code'].unique().tolist()))

(54, 53)

In [23]:
i=list(set(train["Region_Code"].unique().tolist())^set(test["Region_Code"].unique().tolist()))
for j in i:
    if j in train["Region_Code"].unique().tolist(): 
        print(j," exist in train data") 
    else: 
        print(j," not exist in train data")

39.2  exist in train data


In [24]:
import numpy as np
np.sort(train['Region_Code'].unique())

array([ 0. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ,
       11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. , 20. , 21. ,
       22. , 23. , 24. , 25. , 26. , 27. , 28. , 29. , 30. , 31. , 32. ,
       33. , 34. , 35. , 36. , 37. , 38. , 39. , 39.2, 40. , 41. , 42. ,
       43. , 44. , 45. , 46. , 47. , 48. , 49. , 50. , 51. , 52. ])

In [25]:
np.sort(test['Region_Code'].unique())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52.])

In [26]:
train['Region_Code']=train['Region_Code'].replace({39.2:39})
np.sort(train['Region_Code'].unique())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52.])

In [27]:
np.sort(test['Region_Code'].unique())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52.])

In [28]:
len(sorted(train['Policy_Sales_Channel'].unique().tolist())),len(sorted(test['Policy_Sales_Channel'].unique().tolist()))

(152, 151)

In [29]:
list(set(train["Policy_Sales_Channel"].unique().tolist())^set(test["Policy_Sales_Channel"].unique().tolist()))

[5.0, 6.0, 33.0, 144.0, 149.0]

In [30]:
i=list(set(train["Policy_Sales_Channel"].unique().tolist())^set(test["Policy_Sales_Channel"].unique().tolist()))
for j in i:
    if j in train["Policy_Sales_Channel"].unique().tolist(): 
        print(j," exist in train data") 
    else: 
        print(j," not exist in train data")

5.0  exist in train data
6.0  exist in train data
33.0  exist in train data
144.0  not exist in train data
149.0  not exist in train data


In [31]:
np.sort(train['Policy_Sales_Channel'].unique())

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  73.,  74.,  75.,  76.,  78.,  79.,
        80.,  81.,  82.,  83.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,
        93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101., 102., 103.,
       104., 105., 106., 107., 108., 109., 110., 111., 112., 113., 114.,
       115., 116., 117., 118., 119., 120., 121., 122., 123., 124., 125.,
       126., 127., 128., 129., 130., 131., 132., 133., 134., 135., 136.,
       137., 138., 139., 140., 145., 146., 147., 148., 150., 151., 152.,
       153., 154., 155., 156., 157., 158., 159., 16

In [32]:
np.sort(test['Policy_Sales_Channel'].unique())

array([  1.,   2.,   3.,   4.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,
        14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
        25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  34.,  35.,  36.,
        37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
        48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
        59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,
        70.,  71.,  73.,  74.,  75.,  76.,  78.,  79.,  80.,  81.,  82.,
        83.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
        96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
       107., 108., 109., 110., 111., 112., 113., 114., 115., 116., 117.,
       118., 119., 120., 121., 122., 123., 124., 125., 126., 127., 128.,
       129., 130., 131., 132., 133., 134., 135., 136., 137., 138., 139.,
       140., 144., 145., 146., 147., 148., 149., 150., 151., 152., 153.,
       154., 155., 156., 157., 158., 159., 160., 16

In [33]:
test.loc[(test['Policy_Sales_Channel']==144) | 
         (test['Policy_Sales_Channel']==149)]

Gender  Age  Driving_License  Region_Code  Previously_Insured  \
2078459       0   22                1         28.0                   0   
5965690       0   67                1         28.0                   0   
7109272       0   22                1          8.0                   0   

         Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  \
2078459            0               1         42974.0                 149.0   
5965690            1               1         33236.0                 144.0   
7109272            0               1         42974.0                 149.0   

         Vintage  
2078459      225  
5965690      260  
7109272       20

In [34]:
import numpy as np
test['Policy_Sales_Channel']=test['Policy_Sales_Channel'].replace({144:np.NAN,
                                                                   149:np.NAN
    
})
np.sort(test['Policy_Sales_Channel'].unique())

array([  1.,   2.,   3.,   4.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,
        14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
        25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  34.,  35.,  36.,
        37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
        48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
        59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,
        70.,  71.,  73.,  74.,  75.,  76.,  78.,  79.,  80.,  81.,  82.,
        83.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
        96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
       107., 108., 109., 110., 111., 112., 113., 114., 115., 116., 117.,
       118., 119., 120., 121., 122., 123., 124., 125., 126., 127., 128.,
       129., 130., 131., 132., 133., 134., 135., 136., 137., 138., 139.,
       140., 145., 146., 147., 148., 150., 151., 152., 153., 154., 155.,
       156., 157., 158., 159., 160., 163.,  nan])

In [35]:
train[train["Policy_Sales_Channel"].isin([5,6,33])]

Gender  Age  Driving_License  Region_Code  Previously_Insured  \
202578         1   62                1         50.0                   1   
451535         1   22                1          8.0                   0   
844680         1   53                1         28.0                   0   
2674524        1   46                1         28.0                   0   
3613846        0   46                1         28.0                   0   
9854728        0   36                1         28.0                   0   
10981127       0   38                1         14.0                   1   

          Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  \
202578              1               0         36628.0                  33.0   
451535              0               1         39495.0                   6.0   
844680              1               1         44302.0                  33.0   
2674524             2               1         44302.0                  33.0   
3613846             1               1         44302.0                  33.0   
9854728             2               1         30203.0                   5.0   
10981127            1               0         31458.0                  33.0   

          Vintage  Response  
202578         97         0  
451535        189         0  
844680         76         0  
2674524        56         0  
3613846        76         1  
9854728       109         0  
10981127       33         0

In [36]:
train['Policy_Sales_Channel']=train['Policy_Sales_Channel'].replace({5:np.NAN,
                                                                6:np.NAN,
                                                                     33:np.NAN   
})
np.sort(train['Policy_Sales_Channel'].unique())

array([  1.,   2.,   3.,   4.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,
        14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
        25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  34.,  35.,  36.,
        37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
        48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
        59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,
        70.,  71.,  73.,  74.,  75.,  76.,  78.,  79.,  80.,  81.,  82.,
        83.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
        96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
       107., 108., 109., 110., 111., 112., 113., 114., 115., 116., 117.,
       118., 119., 120., 121., 122., 123., 124., 125., 126., 127., 128.,
       129., 130., 131., 132., 133., 134., 135., 136., 137., 138., 139.,
       140., 145., 146., 147., 148., 150., 151., 152., 153., 154., 155.,
       156., 157., 158., 159., 160., 163.,  nan])

In [37]:
np.sort(test['Policy_Sales_Channel'].unique())

array([  1.,   2.,   3.,   4.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,
        14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
        25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  34.,  35.,  36.,
        37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
        48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
        59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,
        70.,  71.,  73.,  74.,  75.,  76.,  78.,  79.,  80.,  81.,  82.,
        83.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
        96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
       107., 108., 109., 110., 111., 112., 113., 114., 115., 116., 117.,
       118., 119., 120., 121., 122., 123., 124., 125., 126., 127., 128.,
       129., 130., 131., 132., 133., 134., 135., 136., 137., 138., 139.,
       140., 145., 146., 147., 148., 150., 151., 152., 153., 154., 155.,
       156., 157., 158., 159., 160., 163.,  nan])

In [38]:
train['Region_Code']=train['Region_Code'].astype('int')
train['Region_Code'].value_counts()

Region_Code
28    3451062
8     1021036
46     578208
41     557581
15     403977
30     367307
29     338146
50     302334
11     278261
36     261946
3      246303
33     232387
47     229190
35     200035
6      181122
45     159292
37     158976
18     148548
39     138069
14     134585
21     126793
10     126081
2      118097
48     114230
13     108838
9       93371
7       92240
12      92142
27      78878
32      78797
43      75868
17      74533
26      71228
25      70556
24      69136
38      60587
0       59274
20      58765
31      58442
16      54905
23      54518
4       52504
49      50822
34      48685
19      44197
22      36932
5       36832
40      35888
1       33966
44      20305
42      13693
52       3450
51       1880
Name: count, dtype: int64

In [39]:
test['Region_Code']=test['Region_Code'].astype('int')
test['Region_Code'].value_counts()

Region_Code
28    2299652
8      681778
46     386147
41     372203
15     268477
30     244864
29     224596
50     201968
11     184821
36     174967
3      164427
33     155735
47     152803
35     133825
6      120975
45     105868
37     105620
18      99023
39      91993
14      90023
21      84503
10      83607
2       78461
48      76381
13      72542
9       62304
7       61745
12      61717
32      52787
27      52315
43      50970
17      49492
26      47810
25      46793
24      46316
38      40562
0       39320
31      39143
20      38648
16      36905
23      36176
4       34954
49      34036
34      32328
19      29253
22      24443
5       24220
40      23831
1       22359
44      13583
42       9042
52       2295
51       1260
Name: count, dtype: int64

In [40]:
for i in ['Region_Code','Policy_Sales_Channel']:
    if (len(list(set(train[i].dropna().unique().tolist())^set(test[i].dropna().unique().tolist())))!=0):
        print(i ,'need to be worked on')
    else:
        continue
print('Done')

Done


In [41]:
train['Annual_Premium'].unique()

array([65101., 58911., 38043., ..., 22112., 54335., 64538.])

In [42]:
train['Annual_Premium']=train['Annual_Premium'].astype('int')
train.head()

Gender  Age  Driving_License  Region_Code  Previously_Insured  Vehicle_Age  \
0       0   21                1           35                   0            1   
1       0   43                1           28                   0            2   
2       1   25                1           14                   1            0   
3       1   35                1            1                   0            1   
4       1   36                1           15                   1            1   

   Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response  
0               1           65101                 124.0      187         0  
1               1           58911                  26.0      288         1  
2               0           38043                 152.0      254         0  
3               1            2630                 156.0       76         0  
4               0           31951                 152.0      294         0

In [43]:
test['Annual_Premium']=test['Annual_Premium'].astype('int')
test.head()

Gender  Age  Driving_License  Region_Code  Previously_Insured  Vehicle_Age  \
0       1   20                1           47                   0            0   
1       0   47                1           28                   0            1   
2       0   47                1           43                   0            1   
3       1   22                1           47                   1            0   
4       0   51                1           19                   0            1   

   Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0               0            2630                 160.0      228  
1               1           37483                 124.0      123  
2               1            2630                  26.0      271  
3               0           24502                 152.0      115  
4               0           34115                 124.0      148

In [44]:
train.isnull().sum()

Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    7
Vintage                 0
Response                0
dtype: int64

In [45]:
test.isnull().sum()

Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    3
Vintage                 0
dtype: int64

In [46]:
train[train.isna().any(axis=1)]

Gender  Age  Driving_License  Region_Code  Previously_Insured  \
202578         1   62                1           50                   1   
451535         1   22                1            8                   0   
844680         1   53                1           28                   0   
2674524        1   46                1           28                   0   
3613846        0   46                1           28                   0   
9854728        0   36                1           28                   0   
10981127       0   38                1           14                   1   

          Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  \
202578              1               0           36628                   NaN   
451535              0               1           39495                   NaN   
844680              1               1           44302                   NaN   
2674524             2               1           44302                   NaN   
3613846             1               1           44302                   NaN   
9854728             2               1           30203                   NaN   
10981127            1               0           31458                   NaN   

          Vintage  Response  
202578         97         0  
451535        189         0  
844680         76         0  
2674524        56         0  
3613846        76         1  
9854728       109         0  
10981127       33         0

In [47]:
test[test.isna().any(axis=1)]

Gender  Age  Driving_License  Region_Code  Previously_Insured  \
2078459       0   22                1           28                   0   
5965690       0   67                1           28                   0   
7109272       0   22                1            8                   0   

         Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  \
2078459            0               1           42974                   NaN   
5965690            1               1           33236                   NaN   
7109272            0               1           42974                   NaN   

         Vintage  
2078459      225  
5965690      260  
7109272       20

In [48]:
train['Policy_Sales_Channel']=train['Policy_Sales_Channel'].fillna(-1)
test['Policy_Sales_Channel']=test['Policy_Sales_Channel'].fillna(-1)
train['Policy_Sales_Channel']=train['Policy_Sales_Channel'].astype('int')
test['Policy_Sales_Channel']=test['Policy_Sales_Channel'].astype('int')
len(sorted(train['Policy_Sales_Channel'].unique().tolist())),len(sorted(test['Policy_Sales_Channel'].unique().tolist()))

(150, 150)

In [49]:
def reduce_mem_usage(df):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.        
    """
    start_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            df[col] = df[col].astype('object')

    end_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

In [50]:
train = reduce_mem_usage(train)
train.info()

Memory usage of dataframe is 965.52 MB
Memory usage after optimization is: 175.55 MB
Decreased by 81.8%
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11504798 entries, 0 to 11504797
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   Gender                int8 
 1   Age                   int8 
 2   Driving_License       int8 
 3   Region_Code           int8 
 4   Previously_Insured    int8 
 5   Vehicle_Age           int8 
 6   Vehicle_Damage        int8 
 7   Annual_Premium        int32
 8   Policy_Sales_Channel  int16
 9   Vintage               int16
 10  Response              int8 
dtypes: int16(2), int32(1), int8(8)
memory usage: 175.5 MB


In [51]:
test = reduce_mem_usage(test)
test.info()

Memory usage of dataframe is 585.16 MB
Memory usage after optimization is: 109.72 MB
Decreased by 81.2%
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7669866 entries, 0 to 7669865
Data columns (total 10 columns):
 #   Column                Dtype
---  ------                -----
 0   Gender                int8 
 1   Age                   int8 
 2   Driving_License       int8 
 3   Region_Code           int8 
 4   Previously_Insured    int8 
 5   Vehicle_Age           int8 
 6   Vehicle_Damage        int8 
 7   Annual_Premium        int32
 8   Policy_Sales_Channel  int16
 9   Vintage               int16
dtypes: int16(2), int32(1), int8(7)
memory usage: 109.7 MB


In [52]:
train['Policy_Sales_Channel'].max()-train['Policy_Sales_Channel'].min(),test['Policy_Sales_Channel'].max()-test['Policy_Sales_Channel'].min(),len(test['Policy_Sales_Channel'].unique().tolist()),len(train['Policy_Sales_Channel'].unique().tolist())

(164, 164, 150, 150)

In [53]:
train['Region_Code'].max()-train['Region_Code'].min(),test['Region_Code'].max()-test['Region_Code'].min(),len(test['Region_Code'].unique().tolist()),len(train['Region_Code'].unique().tolist())

(52, 52, 53, 53)

In [54]:
train[['Region_Code','Policy_Sales_Channel']].describe().apply(lambda s: s.apply('{0:.1f}'.format))

Region_Code Policy_Sales_Channel
count  11504798.0           11504798.0
mean         26.4                112.4
std          13.0                 54.0
min           0.0                 -1.0
25%          15.0                 29.0
50%          28.0                151.0
75%          35.0                152.0
max          52.0                163.0

In [55]:
test[['Region_Code','Policy_Sales_Channel']].describe().apply(lambda s: s.apply('{0:.1f}'.format))

Region_Code Policy_Sales_Channel
count   7669866.0            7669866.0
mean         26.4                112.4
std          13.0                 54.1
min           0.0                 -1.0
25%          15.0                 29.0
50%          28.0                151.0
75%          35.0                152.0
max          52.0                163.0

In [56]:
train.to_csv('./train.csv',index=False)
test.to_csv('./test.csv',index=False)